//Create Forms
export const CREATE_FORM_LOADING = "CREATE_FORM_LOADING";
export const CREATE_FORM_ERROR = "CREATE_FORM_ERROR";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const CREATE_FORM_RESET = "CREATE_FORM_RESET";

//Update Forms
export const UPDATE_FORM_LOADING = "UPDATE_FORM_LOADING";
export const UPDATE_FORM_ERROR = "UPDATE_FORM_ERROR";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const UPDATE_FORM_RESET = "UPDATE_FORM_RESET";

//Delete Forms
export const DELETE_FORM_LOADING = "DELETE_FORM_LOADING";
export const DELETE_FORM_ERROR = "DELETE_FORM_ERROR";
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
export const DELETE_FORM_RESET = "DELETE_FORM_RESET";

//Fetch form details
export const FORM_DETAILS_LOADING= "FORM_DETAILS_LOADING";
export const FORM_DETAILS_ERROR = "FORM_DETAILS_ERROR";
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS";
export const FORM_DETAILS_RESET = "FORM_DETAILS_RESET";

//Fetch user forms
export const USER_FORMS_LOADING= "USER_FORMS_LOADING";
export const USER_FORMS_ERROR = "USER_FORMS_ERROR";
export const USER_FORMS_SUCCESS = "USER_FORMS_SUCCESS";
export const USER_FORMS_RESET = "USER_FORMS_RESET";
export const USER_FORMS_DELETED = "USER_FORMS_DELETED";

//Save user forms inputs
export const FORM_INPUT_SAVING = "FORM_INPUT_SAVING";
export const FORM_INPUT_ERROR = "FORM_INPUT_ERROR";
export const FORM_INPUT_SUCCESS = "FORM_INPUT_SUCCESS";
export const FORM_INPUT_SAVE_RESET = "FORM_INPUT_SAVE_RESET";

//Delete user forms inputs
export const DELETE_FORM_INPUT_LOADING = "DELETE_FORM_INPUT_LOADING";
export const DELETE_FORM_INPUT_ERROR = "DELETE_FORM_INPUT_ERROR";
export const DELETE_FORM_INPUT_SUCCESS = "DELETE_FORM_INPUT_SUCCESS";
export const DELETE_FORM_INPUT_RESET = "DELETE_FORM_INPUT_RESET";

//Get form input details
export const FORM_INPUT_DETAILS_LOADING = "FORM_INPUT_DETAILS_LOADING";
export const FORM_INPUT_DETAILS_ERROR = "FORM_INPUT_DETAILS_ERROR";
export const FORM_INPUT_DETAILS_SUCCESS = "FORM_INPUT_DETAILS_SUCCESS";
export const FORM_INPUT_DETAILS_RESET = "FORM_INPUT_DETAILS_RESET";

//Fetch user forms inputs
export const GET_FORMS_INPUTS_LOADING = "GET_FORMS_INPUTS_LOADING";
export const GET_FORMS_INPUTS_ERROR = "GET_FORMS_INPUTS_ERROR";
export const GET_FORMS_INPUTS_SUCCESS = "GET_FORMS_INPUTS_SUCCESS";
export const GET_FORMS_INPUTS_RESET = "GET_FORMS_INPUTS_RESET";
export const FORMS_INPUTS_DELETED = "FORMS_INPUTS_DELETED";
