# Generated by Django 3.0.3 on 2020-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
