// reset password 
export const RESET_PASSWORD_MAIL_SENT_SUCCESS = "RESET_PASSWORD_MAIL_SENT_SUCCESS";
export const RESET_PASSWORD_INITIATION_FAILED = "RESET_PASSWORD_INITIATION_FAILED";
export const RESET_PASSWORD_INITIATION_LOADING = "RESET_PASSWORD_INITIATION_LOADING";
export const RESET_PASSWORD_CONFIRM_FAILED = "RESET_PASSWORD_CONFIRM_FAILED";
export const RESET_PASSWORD_CONFIRM_LOADING = "RESET_PASSWORD_CONFIRM_LOADING";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";

//auth and userprofile
export const MYPROFILE_LOADED = "MYPROFILE_LOADED";
export const MYPROFILE_LOADING = "MYPROFILE_LOADING";
export const MYPROFILE_UPDATING = "MYPROFILE_UPDATING";
export const MYPROFILE_UPDATED = "MYPROFILE_UPDATED";
export const MYPROFILE_RESET = "MYPROFILE_RESET";
export const MYPROFILE_UPDATE_ERROR = "MYPROFILE_UPDATE_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_VALIDATING = "LOGIN_VALIDATING";